import { PresetTheme, QRStyleConfig } from '../types';

export const DEFAULT_QR_CONFIG: QRStyleConfig = {
  foregroundColor: '#0f172a',
  backgroundColor: '#ffffff',
  transparentBg: false,
  gradientType: 'none',
  gradientColor2: '#3b82f6',
  gradientAngle: 45,
  patternStyle: 'square',
  eyeStyle: 'square',
  eyeBallStyle: 'square',
  eyeColor: '',
  frameStyle: 'none',
  frameText: 'SCAN ME',
  frameColor: '#0f172a',
  frameTextColor: '#ffffff',
  logoUrl: null,
  logoScale: 0.22,
  logoBgColor: '#ffffff',
  logoBgShape: 'circle',
  size: 320,
  margin: 2,
  errorCorrectionLevel: 'M',
};

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'classic-slate',
    name: 'Classic Dark',
    foregroundColor: '#0f172a',
    backgroundColor: '#ffffff',
    gradientType: 'none',
    gradientColor2: '',
    patternStyle: 'square',
    eyeStyle: 'square',
    eyeBallStyle: 'square',
    eyeColor: '',
  },
  {
    id: 'royal-indigo',
    name: 'Royal Sapphire',
    foregroundColor: '#1e1b4b',
    backgroundColor: '#ffffff',
    gradientType: 'linear',
    gradientColor2: '#4f46e5',
    patternStyle: 'rounded',
    eyeStyle: 'rounded',
    eyeBallStyle: 'circle',
    eyeColor: '#312e81',
  },
  {
    id: 'emerald-gradient',
    name: 'Emerald Luxe',
    foregroundColor: '#064e3b',
    backgroundColor: '#f0fdf4',
    gradientType: 'linear',
    gradientColor2: '#10b981',
    patternStyle: 'dots',
    eyeStyle: 'circle',
    eyeBallStyle: 'circle',
    eyeColor: '#047857',
  },
  {
    id: 'sunset-amber',
    name: 'Sunset Glow',
    foregroundColor: '#881337',
    backgroundColor: '#fff1f2',
    gradientType: 'linear',
    gradientColor2: '#f43f5e',
    patternStyle: 'rounded',
    eyeStyle: 'leaf',
    eyeBallStyle: 'diamond',
    eyeColor: '#be123c',
  },
  {
    id: 'cyber-purple',
    name: 'Cyber Violet',
    foregroundColor: '#581c87',
    backgroundColor: '#faf5ff',
    gradientType: 'linear',
    gradientColor2: '#a855f7',
    patternStyle: 'classy',
    eyeStyle: 'shield',
    eyeBallStyle: 'circle',
    eyeColor: '#6b21a8',
  },
  {
    id: 'midnight-gold',
    name: 'Midnight Gold',
    foregroundColor: '#18181b',
    backgroundColor: '#fafafa',
    gradientType: 'linear',
    gradientColor2: '#d97706',
    patternStyle: 'diamond',
    eyeStyle: 'shield',
    eyeBallStyle: 'diamond',
    eyeColor: '#b45309',
  },
  {
    id: 'ocean-cyan',
    name: 'Ocean Breeze',
    foregroundColor: '#0e7490',
    backgroundColor: '#f0fdfa',
    gradientType: 'linear',
    gradientColor2: '#06b6d4',
    patternStyle: 'dots',
    eyeStyle: 'circle',
    eyeBallStyle: 'circle',
    eyeColor: '#0f766e',
  },
];
